version: '3.4'

services:
  azfunction.http:
    image: ${DOCKER_REGISTRY-}azfunctionhttp
    build:
      context: .
      dockerfile: ../src/AzFunction.Http/Dockerfile
  
  azfunction.sb:
    image: ${DOCKER_REGISTRY-}azfunctionsb
    build:
      context: .
      dockerfile: ../src/AzFunction.ServiceBus/Dockerfile
