# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:5100/azfunctionsb
  pullPolicy: Always
  tag: latest

imagePullSecrets: []

autoscaling:
  enabled: true
  minReplicas: 0
  maxReplicas: 5
  pollingInterval: 30
  cooldownPeriod: 15
  triggers:
    azure-servicebus:
      connectionFromEnv: ServiceBusOptions__ConnectionString
      queueName: sb-queue-k8s-az-func
      activationMessageCount: "2"
      messageCount: "5"

# Values for Az Storage Share File
volumeAzStorage:
  prefixName: 
  mountPath: 

# Default values for Health check configuration.
healthchecks:
  servicesLabel: any
  path: /