{{- if .Values.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "az-func-http.fullname" . }}-scaler
spec:
  scaleTargetRef:
    name: {{ include "az-func-http.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas}}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas}}
  pollingInterval: {{ .Values.autoscaling.pollingInterval}}
  cooldownPeriod: {{ .Values.autoscaling.cooldownPeriod}}
  triggers:
  {{- range $key, $value := .Values.autoscaling.triggers }}
    - type: {{ $key }}
    {{- if eq $key "azure-eventhub" }}
      metadata:
        consumerGroup: {{ $value.consumerGroup}}
        connectionFromEnv: {{ $value.connectionFromEnv }}
        storageConnectionFromEnv: {{ $value.storageConnectionFromEnv }}
        {{- if $value.unprocessedEventThreshold }}
        unprocessedEventThreshold: {{ $value.unprocessedEventThreshold | quote }}
        {{- end }} 
        {{- if $value.blobContainer }}
        blobContainer: {{ $value.blobContainer }}
        {{- end }}
        {{- if $value.checkpointStrategy }}
        checkpointStrategy: {{ $value.checkpointStrategy }}
        {{- end }}
    {{- end }} 
  {{- end }} 
{{- end}}